sudo: required
dist: trusty
language: nodejs
node_js:
  - "8.2"
python:
  - "3.4"
before_install:
  - sudo apt-get install -y fabric
script:
  - pip -V
  - python -V
  - node -v
  - npm -v
after_success:
  - fab -l
  - fab deploy

